{
 "title": "gearbox",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "gearbox",
    "query": {
     "query": "SHOW TAG VALUES FROM \"mqtt_consumer\" WITH KEY = \"gearbox\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Acceleration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "accel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration 1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "accel1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration measurements",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"accel\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time(5s) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "accel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acceleration 1 measurements",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 5 },
   "targets": [
    {
     "query": "SELECT mean(\"accel1\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time(5s) fill(null) ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "alerts issued for accel",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "measurement": "alerts_accel0",
     "query": "SELECT time, accel\n  FROM \"alerts_accel0\"\n  WHERE $timeFilter\n  ORDER BY time DESC\n  LIMIT 50\n",
     "select": [
      [
       { "params": [ "accel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "alerts issued for accel1 ",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 11 },
   "targets": [
    {
     "measurement": "alerts_accel1",
     "query": "SELECT time, accel1\n  FROM \"alerts_accel1\"\n  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "accel1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kapacitor Alerts for Accel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"accel\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "accel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts_accel0",
     "query": "SELECT \"accel\" FROM \"alerts_accel0\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "accel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kapacitor Alerts for accel1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 16 },
   "targets": [
    {
     "query": "SELECT mean(\"accel1\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts_accel1",
     "select": [
      [
       { "params": [ "accel1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "temp_dht" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 1, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "temp_dht" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}